FROM docker.io/library/golang:1.22.3-alpine3.18

ARG BUILD_REV
ARG BUILD_DATE
LABEL org.opencontainers.image.title="alwatr/golang" \
      org.opencontainers.image.description="Go (golang) is a general purpose, higher-level, imperative programming language, packaged by Alwatr." \
      org.opencontainers.image.base.name="docker.io/library/golang:1.22.1-alpine3.18" \
      org.opencontainers.image.version="1.22.1" \
      org.opencontainers.image.ref.name="1.22.1" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.created=${BUILD_DATE} \
      org.opencontainers.image.revision=${BUILD_REV} \
      org.opencontainers.image.vendor="Alwatr" \
      org.opencontainers.image.source="https://github.com/Alwatr/containers/tree/next/golang" \
      org.opencontainers.image.url="https://github.com/Alwatr/containers/tree/next/golang" \
      org.opencontainers.image.documentation="https://github.com/Alwatr/containers/tree/next/golang" \
      org.opencontainers.image.authors="S. Ali Mihandoost <ali.mihandoost@gmail.com> (https://ali.mihandoost.com), S. Amir Mohammad Najafi <njfamirm@gmail.com> (https://njfamirm.ir/)" \
      cloud.alwatr.image.version.full="1.22.1" \
      cloud.alwatr.image.version.short="1"
