FROM docker.io/wodby/mariadb:10.11-3.27.1

ARG BUILD_REV
ARG BUILD_DATE
LABEL org.opencontainers.image.title="alwatr/mariadb" \
      org.opencontainers.image.description="MariaDB was designed as a drop-in replacement of MySQL(R) with more features, new storage engines, fewer bugs, and better performance, packaged by Alwatr." \
      org.opencontainers.image.base.name="docker.io/wodby/mariadb:10.11-3.26.5" \
      org.opencontainers.image.version="10.11" \
      org.opencontainers.image.ref.name="10.11-3.26.5" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.created=${BUILD_DATE} \
      org.opencontainers.image.revision=${BUILD_REV} \
      org.opencontainers.image.vendor="Alwatr" \
      org.opencontainers.image.source="https://github.com/Alwatr/containers/tree/next/mariadb" \
      org.opencontainers.image.url="https://github.com/Alwatr/containers/tree/next/mariadb" \
      org.opencontainers.image.documentation="https://github.com/Alwatr/containers/tree/next/mariadb" \
      org.opencontainers.image.authors="S. Ali Mihandoost <ali.mihandoost@gmail.com> (https://ali.mihandoost.com), S. Amir Mohammad Najafi <njfamirm@gmail.com> (https://njfamirm.ir/)" \
      cloud.alwatr.image.version.full="10.11.6" \
      cloud.alwatr.image.version.short="10"
