FROM docker.io/library/traefik:v2.0-alpine

ARG BUILD_REV
ARG BUILD_DATE
LABEL org.opencontainers.image.title="alwatr/traefik" \
      org.opencontainers.image.description="A modern reverse-proxy, packaged by Alwatr." \
      org.opencontainers.image.base.name="docker.io/library/traefik:v1.7.34-alpine" \
      org.opencontainers.image.version="1.7.34" \
      org.opencontainers.image.ref.name="1.7.34-alpine" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.created=${BUILD_DATE} \
      org.opencontainers.image.revision=${BUILD_REV} \
      org.opencontainers.image.vendor="Alwatr" \
      org.opencontainers.image.source="https://github.com/Alwatr/containers/tree/main/traefik" \
      org.opencontainers.image.url="https://github.com/Alwatr/containers/tree/main/traefik" \
      org.opencontainers.image.documentation="https://github.com/Alwatr/containers/tree/main/traefik" \
      org.opencontainers.image.authors="S. Ali Mihandoost <ali.mihandoost@gmail.com> (https://ali.mihandoost.com), S. Amir Mohammad Najafi <njfamirm@gmail.com> (https://njfamirm.ir/)" \
      cloud.alwatr.image.version.full="1.7.34" \
      cloud.alwatr.image.version.short="1"
