# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 20
    reviewers:
      - AliMD
    schedule:
      interval: daily
    labels:
      - ci
      - priority-low
      - maintenance
    groups:
      github-actions:
        patterns:
          - '*'

  # docker images
  - package-ecosystem: docker
    directory: /traefik/1
    reviewers:
      - AliMD
    schedule:
      interval: daily
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /traefik/3
    reviewers:
      - AliMD
    schedule:
      interval: daily
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /alpine
    reviewers:
      - AliMD
    schedule:
      interval: daily
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /nocodb
    reviewers:
      - AliMD
    schedule:
      interval: daily
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /php/7.4-apache
    reviewers:
      - AliMD
    schedule:
      interval: daily
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /php/7.4-fpm
    reviewers:
      - AliMD
    schedule:
      interval: daily
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /php/8.2-fpm
    reviewers:
      - AliMD
    schedule:
      interval: daily
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /adminer
    reviewers:
      - AliMD
    schedule:
      interval: daily
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /mariadb/11
    reviewers:
      - AliMD
    schedule:
      interval: daily
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /mariadb/10
    reviewers:
      - AliMD
    schedule:
      interval: daily
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /wordpress/php7.4
    reviewers:
      - AliMD
    schedule:
      interval: daily
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /wordpress/php8.2
    reviewers:
      - AliMD
    schedule:
      interval: daily
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /tdlib
    reviewers:
      - AliMD
    schedule:
      interval: daily
    labels:
      - ci
      - priority-low
      - maintenance

