# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: weekly
      time: '00:30'
      day: 'tuesday'
    labels:
      - ci
      - priority-low
      - maintenance
    groups:
      github-actions:
        patterns:
          - '*'

  # docker images

  - package-ecosystem: docker
    directory: /traefik/1
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    schedule:
      interval: weekly
      time: '00:30'
      day: 'tuesday'
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /traefik/3
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    schedule:
      interval: weekly
      time: '00:30'
      day: 'tuesday'
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /alpine
    schedule:
      interval: weekly
      time: '00:30'
      day: 'tuesday'
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /nocodb
    schedule:
      interval: weekly
      time: '00:30'
      day: 'tuesday'
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /php/7.4-apache
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    schedule:
      interval: weekly
      time: '00:30'
      day: 'tuesday'
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /php/7.4-fpm
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    schedule:
      interval: weekly
      time: '00:30'
      day: 'tuesday'
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /php/8.2-fpm
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    schedule:
      interval: weekly
      time: '00:30'
      day: 'tuesday'
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /adminer
    schedule:
      interval: weekly
      time: '00:30'
      day: 'tuesday'
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /mariadb/11
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    schedule:
      interval: weekly
      time: '00:30'
      day: 'tuesday'
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /mariadb/10
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    schedule:
      interval: weekly
      time: '00:30'
      day: 'tuesday'
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /wordpress/php7.4
    schedule:
      interval: weekly
      time: '00:30'
      day: 'tuesday'
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /wordpress/php8.2
    schedule:
      interval: weekly
      time: '00:30'
      day: 'tuesday'
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /postgres
    schedule:
      interval: weekly
      time: '00:30'
      day: 'tuesday'
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /node/lts
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    schedule:
      interval: weekly
      time: '00:30'
      day: 'tuesday'
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /opencv
    schedule:
      interval: weekly
      time: '00:30'
      day: 'tuesday'
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /python
    schedule:
      interval: weekly
      time: '00:30'
      day: 'tuesday'
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /golang
    schedule:
      interval: weekly
      time: '00:30'
      day: 'tuesday'
    labels:
      - ci
      - priority-low
      - maintenance

  - package-ecosystem: docker
    directory: /bun
    schedule:
      interval: weekly
      time: '00:30'
      day: 'tuesday'
    labels:
      - ci
      - priority-low
      - maintenance
