FROM docker.io/oven/bun:1.0.35-alpine

ARG BUILD_REV
ARG BUILD_DATE
LABEL org.opencontainers.image.title="alwatr/bun" \
      org.opencontainers.image.description="An all-in-one JavaScript runtime & toolkit designed for speed, complete with a bundler, test runner, and Node.js-compatible package manager, packaged by Alwatr." \
      org.opencontainers.image.base.name="docker.io/oven/bun:1.0.34-alpine" \
      org.opencontainers.image.version="1.0.34" \
      org.opencontainers.image.ref.name="1.0.34" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.created=${BUILD_DATE} \
      org.opencontainers.image.revision=${BUILD_REV} \
      org.opencontainers.image.vendor="Alwatr" \
      org.opencontainers.image.source="https://github.com/Alwatr/containers/tree/next/bun" \
      org.opencontainers.image.url="https://github.com/Alwatr/containers/tree/next/bun" \
      org.opencontainers.image.documentation="https://github.com/Alwatr/containers/tree/next/bun" \
      org.opencontainers.image.authors="S. Ali Mihandoost <ali.mihandoost@gmail.com> (https://ali.mihandoost.com), S. Amir Mohammad Najafi <njfamirm@gmail.com> (https://njfamirm.ir/)" \
      cloud.alwatr.image.version.full="1.0.34" \
      cloud.alwatr.image.version.short="1"
