FROM docker.io/library/wordpress:6.1.1-php7.4-fpm

ARG BUILD_REV
ARG BUILD_DATE
LABEL org.opencontainers.image.title="alwatr/wordpress" \
      org.opencontainers.image.description="A very slow, lazy and stupid CMS for newbies, packaged by Alwatr." \
      org.opencontainers.image.base.name="docker.io/library/wordpress:6.1.1-php7.4-fpm" \
      org.opencontainers.image.version="6.1.1" \
      org.opencontainers.image.ref.name="6.1.1-php7.4-fpm" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.created=${BUILD_DATE} \
      org.opencontainers.image.revision=${BUILD_REV} \
      org.opencontainers.image.vendor="Alwatr" \
      org.opencontainers.image.source="https://github.com/Alwatr/containers/tree/main/wordpress/php7.4" \
      org.opencontainers.image.url="https://github.com/Alwatr/containers/tree/main/wordpress/php7.4" \
      org.opencontainers.image.documentation="https://github.com/Alwatr/containers/tree/main/wordpress" \
      org.opencontainers.image.authors="S. Ali Mihandoost <ali.mihandoost@gmail.com> (https://ali.mihandoost.com), S. Amir Mohammad Najafi <njfamirm@gmail.com> (https://njfamirm.ir/)" \
      cloud.alwatr.image.version.full="6.1.1-php7.4" \
      cloud.alwatr.image.version.short="6-php7"
