FROM docker.io/library/traefik:v3.0.0-beta4

ARG BUILD_REV
ARG BUILD_DATE
LABEL org.opencontainers.image.title="alwatr/traefik" \
      org.opencontainers.image.description="A modern reverse-proxy, packaged by Alwatr." \
      org.opencontainers.image.base.name="docker.io/library/traefik:v3.0.0-beta4" \
      org.opencontainers.image.version="3.0.0-beta4" \
      org.opencontainers.image.ref.name="3.0.0-beta4" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.created=${BUILD_DATE} \
      org.opencontainers.image.revision=${BUILD_REV} \
      org.opencontainers.image.vendor="Alwatr" \
      org.opencontainers.image.source="https://github.com/Alwatr/containers/tree/main/traefik" \
      org.opencontainers.image.url="https://github.com/Alwatr/containers/tree/main/traefik" \
      org.opencontainers.image.documentation="https://github.com/Alwatr/containers/tree/main/traefik" \
      org.opencontainers.image.authors="S. Ali Mihandoost <ali.mihandoost@gmail.com> (https://ali.mihandoost.com), S. Amir Mohammad Najafi <njfamirm@gmail.com> (https://njfamirm.ir/)" \
      ir.alwatr.image.version.full="3.0.0-beta4" \
      ir.alwatr.image.version.short="3"
