FROM docker.io/library/php:8.3.3-fpm

ARG BUILD_REV
ARG BUILD_DATE
LABEL org.opencontainers.image.title="alwatr/php" \
      org.opencontainers.image.description="A slow, lazy and stupid server-side programming language for newbies, packaged by Alwatr." \
      org.opencontainers.image.base.name="docker.io/library/php:8.3.3-fpm" \
      org.opencontainers.image.version="8.3.3" \
      org.opencontainers.image.ref.name="8.3.3-fpm" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.created=${BUILD_DATE} \
      org.opencontainers.image.revision=${BUILD_REV} \
      org.opencontainers.image.vendor="Alwatr" \
      org.opencontainers.image.source="https://github.com/Alwatr/containers/tree/next/php/8.2-fpm" \
      org.opencontainers.image.url="https://github.com/Alwatr/containers/tree/next/php/8.2-fpm" \
      org.opencontainers.image.documentation="https://github.com/Alwatr/containers/tree/next/php" \
      org.opencontainers.image.authors="S. Ali Mihandoost <ali.mihandoost@gmail.com> (https://ali.mihandoost.com), S. Amir Mohammad Najafi <njfamirm@gmail.com> (https://njfamirm.ir/)" \
      cloud.alwatr.image.version.full="8.3.3" \
      cloud.alwatr.image.version.short="8"
