FROM docker.io/wodby/adminer:4.8-3.24.4

ARG BUILD_REV
ARG BUILD_DATE
LABEL org.opencontainers.image.title="alwatr/adminer" \
      org.opencontainers.image.description="Database management in a single PHP file, packaged by Alwatr." \
      org.opencontainers.image.base.name="docker.io/library/adminer:4.8-3.24.4" \
      org.opencontainers.image.version="4.8" \
      org.opencontainers.image.ref.name="4.8-3.24.4" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.created=${BUILD_DATE} \
      org.opencontainers.image.revision=${BUILD_REV} \
      org.opencontainers.image.vendor="Alwatr" \
      org.opencontainers.image.source="https://github.com/Alwatr/containers/tree/main/adminer" \
      org.opencontainers.image.url="https://github.com/Alwatr/containers/tree/main/adminer" \
      org.opencontainers.image.documentation="https://github.com/Alwatr/containers/tree/main/adminer" \
      org.opencontainers.image.authors="S. Ali Mihandoost <ali.mihandoost@gmail.com> (https://ali.mihandoost.com), S. Amir Mohammad Najafi <njfamirm@gmail.com> (https://njfamirm.ir/)"
