FROM docker.io/wodby/mariadb:11.0-3.26.4

ARG BUILD_REV
ARG BUILD_DATE
LABEL org.opencontainers.image.title="alwatr/mariadb" \
      org.opencontainers.image.description="A fork of the MySQL relational database management system, packaged by Alwatr." \
      org.opencontainers.image.base.name="docker.io/wodby/mariadb:11.0-3.26.4" \
      org.opencontainers.image.version="11.0" \
      org.opencontainers.image.ref.name="11.0-3.26.4" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.created=${BUILD_DATE} \
      org.opencontainers.image.revision=${BUILD_REV} \
      org.opencontainers.image.vendor="Alwatr" \
      org.opencontainers.image.source="https://github.com/Alwatr/containers/tree/main/mariadb" \
      org.opencontainers.image.url="https://github.com/Alwatr/containers/tree/main/mariadb" \
      org.opencontainers.image.documentation="https://github.com/Alwatr/containers/tree/main/mariadb" \
      org.opencontainers.image.authors="S. Ali Mihandoost <ali.mihandoost@gmail.com> (https://ali.mihandoost.com), S. Amir Mohammad Najafi <njfamirm@gmail.com> (https://njfamirm.ir/)" \
      cloud.alwatr.image.version.full="11.0-3.26.4" \
      cloud.alwatr.image.version.short="11"
