FROM docker.io/library/wordpress:6.5.4-php8.2-fpm

ARG BUILD_REV
ARG BUILD_DATE
LABEL org.opencontainers.image.title="alwatr/wordpress" \
      org.opencontainers.image.description="A very slow, lazy and stupid CMS for newbies, packaged by Alwatr." \
      org.opencontainers.image.base.name="docker.io/library/wordpress:6.4.3-php8.2-fpm" \
      org.opencontainers.image.version="6.4.3" \
      org.opencontainers.image.ref.name="6.4.3-php8.2-fpm" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.created=${BUILD_DATE} \
      org.opencontainers.image.revision=${BUILD_REV} \
      org.opencontainers.image.vendor="Alwatr" \
      org.opencontainers.image.source="https://github.com/Alwatr/containers/tree/next/wordpress/php8.2" \
      org.opencontainers.image.url="https://github.com/Alwatr/containers/tree/next/wordpress/php8.2" \
      org.opencontainers.image.documentation="https://github.com/Alwatr/containers/tree/next/wordpress" \
      org.opencontainers.image.authors="S. Ali Mihandoost <ali.mihandoost@gmail.com> (https://ali.mihandoost.com), S. Amir Mohammad Najafi <njfamirm@gmail.com> (https://njfamirm.ir/)" \
      cloud.alwatr.image.version.full="6.4.3" \
      cloud.alwatr.image.version.short="6"
