FROM docker.io/nocodb/nocodb:0.207.0

ARG BUILD_REV
ARG BUILD_DATE
LABEL org.opencontainers.image.title="alwatr/nocodb" \
      org.opencontainers.image.description="A free, open-source, self-hosted, and extensible database management tool that helps you easily manage and visualize your data, packaged by Alwatr." \
      org.opencontainers.image.base.name="docker.io/wodby/nocodb:0.204.9" \
      org.opencontainers.image.version="0.204.9" \
      org.opencontainers.image.ref.name="0.204.9" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.created=${BUILD_DATE} \
      org.opencontainers.image.revision=${BUILD_REV} \
      org.opencontainers.image.vendor="Alwatr" \
      org.opencontainers.image.source="https://github.com/Alwatr/containers/tree/next/nocodb" \
      org.opencontainers.image.url="https://github.com/Alwatr/containers/tree/next/nocodb" \
      org.opencontainers.image.documentation="https://github.com/Alwatr/containers/tree/next/nocodb" \
      org.opencontainers.image.authors="S. Ali Mihandoost <ali.mihandoost@gmail.com> (https://ali.mihandoost.com), S. Amir Mohammad Najafi <njfamirm@gmail.com> (https://njfamirm.ir/)" \
      cloud.alwatr.image.version.full="0.204.9" \
      cloud.alwatr.image.version.short="0"
