FROM docker.io/wodby/postgres:16-1.33.1

ARG BUILD_REV
ARG BUILD_DATE
LABEL org.opencontainers.image.title="alwatr/postgres" \
      org.opencontainers.image.description="Alpine-based PostgreSQL container image with orchestrations, packaged by Alwatr." \
      org.opencontainers.image.base.name="docker.io/wodby/postgres:15-1.32.0" \
      org.opencontainers.image.version="16.1" \
      org.opencontainers.image.ref.name="15-1.32.0" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.created=${BUILD_DATE} \
      org.opencontainers.image.revision=${BUILD_REV} \
      org.opencontainers.image.vendor="Alwatr" \
      org.opencontainers.image.source="https://github.com/Alwatr/containers/tree/next/postgres" \
      org.opencontainers.image.url="https://github.com/Alwatr/containers/tree/next/postgres" \
      org.opencontainers.image.documentation="https://github.com/Alwatr/containers/tree/next/postgres" \
      org.opencontainers.image.authors="S. Ali Mihandoost <ali.mihandoost@gmail.com> (https://ali.mihandoost.com), S. Amir Mohammad Najafi <njfamirm@gmail.com> (https://njfamirm.ir/)" \
      cloud.alwatr.image.version.full="16.1" \
      cloud.alwatr.image.version.short="16"
