FROM docker.io/library/php:7.4-fpm

ARG BUILD_REV
ARG BUILD_DATE
LABEL org.opencontainers.image.title="alwatr/php" \
      org.opencontainers.image.description="A very slow, lazy and stupid server-side programming language for newbies, packaged by Alwatr." \
      org.opencontainers.image.base.name="docker.io/php:7.4-fpm" \
      org.opencontainers.image.version="7.4-fpm" \
      org.opencontainers.image.ref.name="7.4-fpm" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.created=${BUILD_DATE} \
      org.opencontainers.image.revision=${BUILD_REV} \
      org.opencontainers.image.vendor="Alwatr" \
      org.opencontainers.image.source="https://github.com/Alwatr/containers/tree/main/php/7.4-fpm" \
      org.opencontainers.image.url="https://github.com/Alwatr/containers/tree/main/php/7.4-fpm" \
      org.opencontainers.image.documentation="https://github.com/Alwatr/containers/tree/main/php" \
      org.opencontainers.image.authors="S. Ali Mihandoost <ali.mihandoost@gmail.com> (https://ali.mihandoost.com), S. Amir Mohammad Najafi <njfamirm@gmail.com> (https://njfamirm.ir/)"
